version: "3"
services:
  source_host:
    image: xonssh/xxh-tests
    hostname: source_host
    depends_on:
      - target_host
    volumes:
      - .:/xxh-tests

  target_host:
    image: rastasheep/ubuntu-sshd:18.04
    hostname: target_host
    entrypoint: /bin/sh -c "cp /xxh-tests/keys/id_rsa.pub /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys && chmod 0600 /root/.ssh/authorized_keys && /usr/sbin/sshd -D"
    volumes:
      - .:/xxh-tests
