version: "3"
services:
  start:
    hostname: start
    image: xonssh/xxh-dev-ubuntu
    depends_on:
      - ubuntu_k
      - ubuntu_kf
      - arch_p
    volumes:
      - .:/xxh-dev
    working_dir: /xxh-dev

  ubuntu_k:
    hostname: ubuntu_k
    image: rastasheep/ubuntu-sshd:18.04  # https://github.com/rastasheep/ubuntu-sshd
    entrypoint: /bin/sh -c "cp /xxh-dev/keys/id_rsa.pub /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys && chmod 0600 /root/.ssh/authorized_keys && /usr/sbin/sshd -D"
    volumes:
      - .:/xxh-dev

  ubuntu_kf:
    hostname: ubuntu_kf
    image: rastasheep/ubuntu-sshd:18.04  # https://github.com/rastasheep/ubuntu-sshd
    entrypoint: /bin/sh -c "apt update && apt install -y fuse && cp /xxh-dev/keys/id_rsa.pub /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys && chmod 0600 /root/.ssh/authorized_keys && /usr/sbin/sshd -D"
    volumes:
      - .:/xxh-dev
    cap_add:
      - SYS_ADMIN
      - MKNOD
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

  arch_p:
    hostname: arch_p
    image: yantis/archlinux-small-ssh-hpn  # https://github.com/yantis/docker-archlinux-ssh-hpn
    volumes:
      - .:/xxh-dev


#  # Alpine is not supported (https://github.com/AppImage/AppImageKit/issues/1015)
#  alpine_p:
#    hostname: alpine_without_fuse
#    image: linuxserver/openssh-server
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - USER_NAME=luke
#      - USER_PASSWORD=skywalker
#      - PASSWORD_ACCESS=true
#      - SUDO_ACCESS=true
#      - PUBLIC_KEY_FILE=/xxh-dev/keys/id_rsa.pub
#    volumes:
#      - .:/xxh-dev