version: "3"
services:
  tatooine:
    image: xonssh/xxh-tests
    hostname: tatooine
    depends_on:
      - hoth
      - dagobah
    volumes:
      - .:/xxh-tests
    working_dir: /xxh-tests

  hoth:
    image: rastasheep/ubuntu-sshd:18.04
    hostname: hoth
    entrypoint: /bin/sh -c "cp /xxh-tests/keys/id_rsa.pub /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys && chmod 0600 /root/.ssh/authorized_keys && /usr/sbin/sshd -D"
    volumes:
      - .:/xxh-tests

  dagobah:
    image: rastasheep/ubuntu-sshd:18.04
    hostname: dagobah
    entrypoint: /bin/sh -c "cp /xxh-tests/keys/id_rsa.pub /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys && chmod 0600 /root/.ssh/authorized_keys && /usr/sbin/sshd -D"
    volumes:
      - .:/xxh-tests

#  # Alpine is not supported (https://github.com/AppImage/AppImageKit/issues/1015)
#  bespin:
#    image: linuxserver/openssh-server
#    hostname: bespin
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - USER_NAME=luke
#      - USER_PASSWORD=skywalker
#      - PASSWORD_ACCESS=true
#      - SUDO_ACCESS=true
#      - PUBLIC_KEY_FILE=/xxh-tests/keys/id_rsa.pub
#    volumes:
#      - .:/xxh-tests