version: "3"
services:
  source_host:
    image: xonssh/xxh-tests
    hostname: source_host
    depends_on:
      - target_host
    volumes:
      - .:/xxh-tests

  # Ubuntu
  target_host:
    image: rastasheep/ubuntu-sshd:18.04
    hostname: target_host
    entrypoint: /bin/sh -c "cp /xxh-tests/keys/id_rsa.pub /root/.ssh/authorized_keys && chown root:root /root/.ssh/authorized_keys && chmod 0600 /root/.ssh/authorized_keys && /usr/sbin/sshd -D"
    volumes:
      - .:/xxh-tests

#  # Alpine is not supported (https://github.com/AppImage/AppImageKit/issues/1015)
#  target_host:
#    image: linuxserver/openssh-server
#    hostname: target_host
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=Europe/London
#      - USER_NAME=snail
#      - USER_PASSWORD=pass
#      - PASSWORD_ACCESS=true
#      - SUDO_ACCESS=true
#      - PUBLIC_KEY_FILE=/xxh-tests/keys/id_rsa.pub
#    volumes:
#      - .:/xxh-tests